# Generated by Django 4.0.6 on 2022-07-25 07:36

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(srid=4326, verbose_name='Area polygon')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Area name')),
            ],
        ),
    ]
