version: '2.1'

volumes:
  postgis-data:


services:
  web:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: areas_dev
    command: bash docker/entrypoint.sh
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always

  db:
    image: postgis/postgis:latest
    volumes:
      - postgis-data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting
    env_file:
      - .env
    ports:
      - "5432:5432"
    expose:
      - 5432
    restart: on-failure