# Generated by Django 4.0.6 on 2022-07-25 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0002_courier_current_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courier',
            name='current_location',
        ),
    ]
