# Generated by Django 4.0.6 on 2022-07-25 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
        ('couriers', '0003_remove_courier_current_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='couriers', to='areas.area'),
        ),
    ]
