# Generated by Django 4.0.6 on 2022-07-25 10:29

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('couriers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Destination point')),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('In delivery', 'In delivery'), ('Done', 'Done')], default='Paid', max_length=64, verbose_name='Status')),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='couriers.courier', verbose_name='Responsible courier')),
            ],
        ),
    ]
